import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import Layout from "../ui/molecules/Layout";

const NotFoundPage: NextPage = () => (
  <Layout>
    <Head>
      <title>404: Not found</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.png" />
    </Head>
    <h1>NOT FOUND</h1>
    <p>You just hit a route that doesn't exist... the sadness.</p>
  </Layout>
);

export default NotFoundPage;
