import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import { Heading, Text } from "@chakra-ui/react";
import Layout from "../ui/molecules/Layout";

const NotFoundPage: NextPage = () => (
  <Layout>
    <Head>
      <title>404: Not found</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/logo.png" />
    </Head>
    <Heading as="h1">
      NOT FOUND
    </Heading>
    <Text>
      You just hit a route that doesn't exist... the sadness.
    </Text>
  </Layout>
);

export default NotFoundPage;
