import type {GetStaticProps, NextPage} from "next";
import Head from "next/head";
import { Box } from "@chakra-ui/react";
import Layout from "../ui/molecules/Layout";
import { getAllPosts } from "../lib/api";
import Post from "../types/Post";
import PostPreview from "../ui/molecules/PostPreview";

type Props = {
  allPosts: Post[],
}

const Home: NextPage<Props> = ({
  allPosts,
}) => {
  return (
    <Layout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.png" />
      </Head>
      {/*<Box*/}
      {/*  sx={{*/}
      {/*    marginBottom: "16px",*/}
      {/*  }}*/}
      {/*>*/}
      {/*  <Heading>*/}
      {/*    Game Engine Tutorial Series*/}
      {/*  </Heading>*/}
      {/*</Box>*/}
      <Box
        sx={{
          display: "flex",
          flexDirection: "column",
          gap: {
            base: "8px",
            sm: "16px",
          },
        }}
      >
        {
          allPosts.map((post, index) => (
            <PostPreview
              key={index}
              title={post.title}
              coverImage={post.coverImage}
              date={post.date}
              excerpt={post.excerpt}
              slug={post.slug}
            />
          ))
        }
      </Box>
    </Layout>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const allPosts = getAllPosts([
    "title",
    "date",
    "slug",
    "author",
    "coverImage",
    "excerpt",
  ]);

  return {
    props: { allPosts },
  };
};

export default Home;
